### ISSUE TITLE
X [ERROR] No matching export in "node_modules/.pnpm/vue-demi@0.14.5_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"

### ISSUE THREAD

**Issue by siyamhosan** [MoterHaker/opensubmitter#12]
Just cloned the repo and tried to run it in windows.

```
X [ERROR] No matching export in "node_modules/.pnpm/vue-demi@0.14.5_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"

    node_modules/.pnpm/pinia@2.1.4_typescript@5.0.2_vue@3.2.47/node_modules/pinia/dist/pinia.mjs:6:9:    
      6 │ import { hasInjectionContext, inject, toRaw, watch, unref, markRaw, effectScope, ref, isVue... 
        ╵          ~~~~~~~~~~~~~~~~~~~

D:\Devloper project\test\opensubmitter\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1604
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/.pnpm/pinia@2.1.4_typescript@5.0.2_vue@3.2.47/node_modules/pinia/dist/pinia.mjs:6:9: ERROR: 
No matching export in "node_modules/.pnpm/vue-demi@0.14.5_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"
    at failureErrorWithLog (D:\Devloper project\test\opensubmitter\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1604:15)
    at D:\Devloper project\test\opensubmitter\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1056:28
    at runOnEndCallbacks (D:\Devloper project\test\opensubmitter\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1476:61)
    at buildResponseToResult (D:\Devloper project\test\opensubmitter\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1054:7)
    at D:\Devloper project\test\opensubmitter\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1166:14
    at responseCallbacks.<computed> (D:\Devloper project\test\opensubmitter\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:701:9)
    at handleIncomingPacket (D:\Devloper project\test\opensubmitter\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:756:9)
    at Socket.readFromStdout (D:\Devloper project\test\opensubmitter\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 9,
        file: 'node_modules/.pnpm/pinia@2.1.4_typescript@5.0.2_vue@3.2.47/node_modules/pinia/dist/pinia.mjs',
        length: 19,
        line: 6,
        lineText: "import { hasInjectionContext, inject, toRaw, watch, unref, markRaw, effectScope, ref, 
isVue2, isRef, isReactive, set, getCurrentScope, onScopeDispose, getCurrentInstance, reactive, toRef, del, nextTick, computed, toRefs } from 'vue-demi';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/.pnpm/vue-demi@0.14.5_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"'
    }
  ],
  warnings: []
}

Node.js v20.3.1
```

also sir, I saw your captcha bypass repo.
so I was making a web automation for purchasing some item in a website there I faced geo.captcha-delivery I tried with all I know but failed to solve or bypass the captcha.

if you want sir can you please help me! please.

**Comment by MoterHaker** [comment]
The project is still new and running on Node v18. The error is related to external pinia module.
